name: Daily Billing Reminders

on:
  schedule:
    # Runs daily at 9:00 AM UTC (adjust as needed for your timezone)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Reminders
        run: |
          curl -X POST \
            ${{ secrets.NEXT_PUBLIC_APP_URL }}/api/admin/daily-reminders \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" \
            -H "Content-Type: application/json" 